version: '3.7'
services:
  database:
    build:
      context: ./database/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./database/volumes:/var/lib/mysql
    networks:
      - docker-sample-project-network
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend/:/backend/
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      - docker-sample-project-network
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - docker-sample-project-network

networks:
  docker-sample-project-network: